version: "3"
services:
  build:
    image: golang:1.21-alpine
    volumes:
      - ./:/go/src/buildenv
  vault:
    image: hashicorp/vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: test
    ports:
      - 8200:8200
